ProjectEnterprise/Models/Entities/PersonSubject.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace ProjectEnterprise.Models.Entities
{
    public class PersonSubject
    {
        public virtual int Id { get; set; }
        public virtual string FirstName { get; set; }
        public virtual string LastName { get; set; }
        public virtual string PhoneNumber { get; set; }
    }
}

ProjectEnterprise/Controllers/PersonSubjectController.cs
using NHibernate;
using NHibernate.Linq;
using ProjectEnterprise.Models.Entities;
using ProjectEnterprise.Models.NHibernate.Mapping;
using System;
using System.Linq;
using System.Web.Mvc;

namespace ProjectEnterprise.Controllers
{
    public class PersonSubjectController : Controller
    {
        public ActionResult GetList()
        {
            using (var session = NHibernateHelper.OpenSession())
            {
                var people = session.Query<PersonSubject>().ToList();
                return View(people);
            }
        }

        public ActionResult Create()
        {
            return View();
        }
        [HttpPost]
        public ActionResult Create(PersonSubject person)
        {
            using (var session = NHibernateHelper.OpenSession())
            using (var transaction = session.BeginTransaction())
            {
                var enterprise = new EnterpriseSubject
                {
                    Id = person.Id.ToString(),
                    Code = GenerateCode(session),
                    Name = $"{person.FirstName} {person.LastName}",
                    SubjectType = 1
                };

                session.Save(enterprise);
                session.Save(person);
                transaction.Commit();
            }
            return RedirectToAction("GetList");
        }


        public ActionResult Edit(int id)
        {
            using (var session = NHibernateHelper.OpenSession())
            {
                var person = GetById(id);
                if (person == null)
                {
                    return HttpNotFound();
                }
                return View(person);
            }
        }
        [HttpPost]
        public ActionResult Edit(PersonSubject person)
        {
            using (var session = NHibernateHelper.OpenSession())
            using (var transaction = session.BeginTransaction())
            {
                var existingPerson = GetById(person.Id);
                if (existingPerson != null)
                {
                    existingPerson.FirstName = person.FirstName;
                    existingPerson.LastName = person.LastName;
                    existingPerson.PhoneNumber = person.PhoneNumber;

                    var enterprise = session.Get<EnterpriseSubject>(person.Id);
                    if (enterprise != null)
                    {
                        enterprise.Name = $"{person.FirstName} {person.LastName}";
                    }

                    session.Update(existingPerson);
                    session.Update(enterprise);
                    transaction.Commit();
                }
            }
            return RedirectToAction("GetList");
        }

        public ActionResult Delete()
        {
            return View();
        }
        [HttpPost]
        public ActionResult Delete(int id)
        {
            using (var session = NHibernateHelper.OpenSession())
            using (var transaction = session.BeginTransaction())
            {
                var person = GetById(id);
                if (person != null)
                {
                    session.Delete(person);
                    var enterprise = session.Get<EnterpriseSubject>(id);
                    if (enterprise != null)
                    {
                        session.Delete(enterprise);
                    }
                    transaction.Commit();
                }
            }
            return RedirectToAction("GetList");
        }


        public PersonSubject GetById(int id)
        {
            using (var session = NHibernateHelper.OpenSession())
            {
                var person = session.Get<PersonSubject>(id);
                return person;
            }
        }

        private string GenerateCode(ISession session)
        {
            var maxCode = session.Query<EnterpriseSubject>().Max(es => (int?)Convert.ToInt32(es.Code)) ?? 0;
            return (maxCode + 1).ToString();
        }
    }

}

ProjectEnterprise/Views/PersonSubject/Create.cshtml
@model ProjectEnterprise.Models.Entities.PersonSubject
@{
    ViewBag.Title = "Create";
}

<h2>Create Person</h2>

@using (Html.BeginForm("Create", "PersonSubject", method: FormMethod.Post))
{
    @Html.ValidationSummary(true)
    <div class="form-group">
        @Html.LabelFor(m => m.FirstName)
        @Html.TextBoxFor(m => m.FirstName, new { @class = "form-control" })
        @Html.ValidationMessageFor(m => m.FirstName)
    </div>
    <div class="form-group">
        @Html.LabelFor(m => m.LastName)
        @Html.TextBoxFor(m => m.LastName, new { @class = "form-control" })
        @Html.ValidationMessageFor(m => m.LastName)
    </div>
    <div class="form-group">
        @Html.LabelFor(m => m.PhoneNumber)
        @Html.TextBoxFor(m => m.PhoneNumber, new { @class = "form-control" })
        @Html.ValidationMessageFor(m => m.PhoneNumber)
    </div>
    <button type="submit" class="btn btn-primary">Create</button>
}

ProjectEnterprise/Views/PersonSubject/Delete.cshtml
@model ProjectEnterprise.Models.Entities.PersonSubject
@{
    ViewBag.Title = "Delete";
}



<h2>Delete Person</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>@Model.FirstName @Model.LastName</h4>
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(m => m.PhoneNumber)
        </dt>
        <dd>
            @Html.DisplayFor(m => m.PhoneNumber)
        </dd>
    </dl>
</div>

@using (Html.BeginForm("Delete", "PersonSubject", method:FormMethod.Post))
{
    @Html.HiddenFor(m => m.Id)
    <button type="submit" class="btn btn-danger>Delete</button>
}

ProjectEnterprise/Views/PersonSubject/Edit.cshtml
@model ProjectEnterprise.Models.Entities.PersonSubject
@{
    ViewBag.Title = "Edit";
}



<h2>Edit Person</h2>

@using (Html.BeginForm("Edit", "PersonSubject", method: FormMethod.Post))
{
    @Html.ValidationSummary(true)
    @Html.HiddenFor(m => m.Id)
    <div class="form-group">
        @Html.LabelFor(m => m.FirstName)
        @Html.TextBoxFor(m => m.FirstName, new { @class = "form-control" })
        @Html.ValidationMessageFor(m => m.FirstName)
    </div>
    <div class="form-group">
        @Html.LabelFor(m => m.LastName)
        @Html.TextBoxFor(m => m.LastName, new { @class = "form-control" })
        @Html.ValidationMessageFor(m => m.LastName)
    </div>
    <div class="form-group">
        @Html.LabelFor(m => m.PhoneNumber)
        @Html.TextBoxFor(m => m.PhoneNumber, new { @class = "form-control" })
        @Html.ValidationMessageFor(m => m.PhoneNumber)
    </div>
    <button type="submit" class="btn btn-primary">Save</button>
}

ProjectEnterprise/Views/PersonSubject/GetList.cshtml
@model IEnumerable<ProjectEnterprise.Models.Entities.PersonSubject>

@{
    ViewBag.Title = "GetList";
}

<h2>GetList</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.FirstName)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.LastName)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.PhoneNumber)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model)
{
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.FirstName)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.LastName)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.PhoneNumber)
        </td>
        <td>
            @Html.ActionLink("Edit", "Edit", new { id=item.Id }) |
            @Html.ActionLink("Details", "Details", new { id=item.Id }) |
            @Html.ActionLink("Delete", "Delete", new { id=item.Id })
        </td>
    </tr>
}

</table>